name: Build Deploy
on:
  push:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Sending failure notification
        uses: ryadom/action_telegram_send_message@0599f7fcf7abee639f411f7eb7260a38cfc40218
        with:
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          chat: "-1001594725259"
          message: "🙁 Failed to create frontend2 Release ${{ github.run_number }}.\nProbably there are no new changes to release."
      - name: Notification
        if: cancelled() == false
        uses: ryadom/action_telegram_build_notification@main
        with:
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          chat: "72314531"
          status: ${{ job.status }}
