name: Build Deploy
on:
  push:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notification
        if: cancelled() == false
        uses: ryadom/telegram_notification@d063b7e7c16bf2387dba7aab61d3c646664e2adc
        with:
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          chat: "72314531"
          status: ${{ job.status }}

