name: Build Deploy
on:
  push:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notification
        if: cancelled() == false
        uses: ryadom/telegram_notification@f00bc07716395df9d9171b460b55fe78a3cab3e4
        with:
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          chat: "72314531"
          status: ${{ job.status }}

