name: Build Deploy
on:
  push:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Message
        uses: ryadom/action_telegram_send_message@f17528c8cfb86b7fee1329a2e0c755beb5f16f02
        with:
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          chat: "72314531"
          message: "hello loh"
      - name: Notification
        if: cancelled() == false
        uses: ryadom/action_telegram_build_notification@2790f6a742c0bb3392e8504d84aa897225d8327a
        with:
          token: ${{ secrets.TELEGRAM_API_TOKEN }}
          chat: "72314531"
          status: ${{ job.status }}
