name: Release Merge
on:
  issue_comment:
    types: [created]
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_CONTEXT"
